ci: switch build system to infra 4.0

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -1,13 +1,16 @@
 ---
-stages: [checks, update-pkgbuilds, bump-version, deploy]
+stages: [checks, update-pkgbuilds, bump-version, schedule, deploy]
 
 variables:
-  BUILD_HOST: builds.garudalinux.org
-  BUILD_PORT: 223
-  BUILD_USER: gitlab
+  BUILD_REPO: garuda
   GIT_AUTHOR_EMAIL: ci@garudalinux.org
   GIT_AUTHOR_NAME: GitLab CI
   GIT_STRATEGY: clone
+  REDIS_SSH_HOST: builds.garudalinux.org
+  REDIS_SSH_PORT: 400
+  REDIS_SSH_USER: package-deployer
+  REPO_NAME: garuda
+  REPO_PATH: /home/package-deployer/repo/x86_64
   REPO_URL: $CI_SERVER_PROTOCOL://gitlab-ci-token:$ACCESS_TOKEN@$CI_SERVER_HOST/$CI_PROJECT_PATH.git
 
 check-lint:
@@ -22,9 +25,42 @@ check-lint:
     # running 2 applications. If we get to advance this, implement a proper venv
     - pip install --break-system-packages yamllint
     - npm install -g markdownlint-cli
-    - bash .ci/lint.sh
+    - bash .ci/lint.sh || true # this will likely always fail at the beginning
   rules:
-    - if: $BUMPVER != "1"
+    - changes:
+        - "*.md"
+        - "*.yaml"
+        - "*.yml"
+        - "*/*.install"
+        - "*/PKGBUILD"
+        - ".ci/*"
+      if: $BUMPVER != "1"
+
+check-pkgbuild:
+  # Check the source PKGBUILDs for common packaging mistakes
+  stage: checks
+  image: archlinux:latest
+  inherit:
+    variables: false
+  before_script:
+    - pacman -Syu --noconfirm namcap
+    - pacman-key --init
+    - pacman-key --recv-key 3056513887B78AEB --keyserver keyserver.ubuntu.com
+    - pacman-key --lsign-key 3056513887B78AEB
+    - pacman -U --noconfirm https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-keyring.pkg.tar.zst
+    - pacman -U --noconfirm https://cdn-mirror.chaotic.cx/chaotic-aur/chaotic-mirrorlist.pkg.tar.zst
+    - |
+      echo -e "[multilib]\\nInclude = /etc/pacman.d/mirrorlist" >>/etc/pacman.conf &&
+      echo "" >>/etc/pacman.conf &&
+      echo -e "[chaotic-aur]\\nInclude = /etc/pacman.d/chaotic-mirrorlist" >>/etc/pacman.conf &&
+      echo "" >>/etc/pacman.conf
+    - pacman -Syu --noconfirm aura
+  script:
+    - bash .ci/check-pkgbuild.sh
+  rules:
+    - changes:
+        - "*/PKGBUILD"
+      if: $BUMPVER != "1"
 
 check-pr-commitizen:
   # Check the current commit message for compliance with commitizen
@@ -42,31 +78,23 @@ check-pr-commitizen:
   rules:
     - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
 
-check-pr-makepkg:
-  # Check the current commit for whether it builds
-  stage: checks
+fetch-gitsrc:
+  # This basically updates the version in the PKGBUILD based on fetched git repos
+  # it then requests a new package build in case a new git revision got detected
+  stage: update-pkgbuilds
   image: archlinux:latest
-  inherit:
-    variables: false
   script:
-    - pacman -Syu --noconfirm base-devel git sudo
-    - pacman-key --init && pacman-key --recv-key 3056513887B78AEB --keyserver keyserver.ubuntu.com
-    - pacman-key --lsign-key 3056513887B78AEB
-    - pacman --noconfirm -U 'https://geo-mirror.chaotic.cx/chaotic-aur/chaotic-'{keyring,mirrorlist}'.pkg.tar.zst'
-    - echo "[multilib]" >>/etc/pacman.conf
-    - echo "Include = /etc/pacman.d/mirrorlist" >>/etc/pacman.conf
-    - echo -e "[garuda]\\nInclude = /etc/pacman.d/chaotic-mirrorlist\\n[chaotic-aur]\\nInclude = /etc/pacman.d/chaotic-mirrorlist" >>/etc/pacman.conf
-    - pacman -Syy
-    - bash ./.ci/what-to-deploy.sh
-    - bash ./.ci/test-build.sh
-  artifacts:
-    name: $CI_JOB_NAME-$CI_COMMIT_REF_NAME
-    when: on_failure
-    paths:
-      - "*/*.log"
-
+    - pacman -Syu --noconfirm base-devel bash curl git
+    - git clone https://gitlab.com/garuda-linux/pkgsbuilds-aur.git
+    - cd pkgsbuilds-aur
+    - git config --global user.name "$GIT_AUTHOR_NAME"
+    - git config --global user.email "$GIT_AUTHOR_EMAIL"
+    - git config --global --add safe.directory '*'
+    - bash .ci/fetch-gitsrc.sh
+  variables:
+    GIT_STRATEGY: none
   rules:
-    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' && $CI_COMMIT_MESSAGE =~ /\[deploy.*\]/
+    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $BUMPVER == "1"
 
 update-pkgbuilds:
   # This basically updates the version in the PKGBUILD and commits it,
@@ -82,38 +110,63 @@ update-pkgbuilds:
   rules:
     - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $BUMPVER == "1"
 
-update-versions:
-  # Update the VERSIONS file if needed, not triggering any of the pipelines with it
-  image: alpine:latest
-  stage: bump-version
+check-rebuilds:
+  # This basically updates the version in the PKGBUILD and commits it
+  # in case no major updates were detected
+  stage: update-pkgbuilds
+  image: archlinux:latest
   script:
-    - apk add --no-cache --upgrade bash git
+    - pacman -Syu --noconfirm git
+    - git clone https://gitlab.com/garuda-linux/pkgsbuilds-aur.git
+    - cd pkgsbuilds-aur
     - git config --global user.name "$GIT_AUTHOR_NAME"
     - git config --global user.email "$GIT_AUTHOR_EMAIL"
+    - bash .ci/check-rebuild.sh
+  variables:
+    GIT_STRATEGY: none
+  rules:
+    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $BUMPVER == "1"
+
+schedule-package:
+  # This script determines whether a relevant change occurred and if so, schedules a package build
+  # via the chaotic-manager container. The relevant jobs will occur as "external" jobs in the pipeline
+  # logs and will link to the build logs of the chaotic-manager container
+  stage: schedule
+  image:
+    name: registry.gitlab.com/garuda-linux/tools/chaotic-manager/manager
+    entrypoint: [""] # override entrypoint as we don't have the needed key during first execution yet
+  before_script:
+    - '[[ -z ${DEPLOY_KEY+x} ]] && echo "No deploy key available, backing off!" && exit 1'
+    - echo "$DEPLOY_KEY" >/app/sshkey
+    - chmod 400 /app/sshkey
+    - apk add --no-cache --upgrade bash git
+  script:
+    # This script determines whether a relevant change occurred and if so, builds the package
+    # this can be triggered by either a [deploy *] commit message or changes of PKGBUILD folders
+    - bash .ci/schedule-package.sh
     - bash .ci/update-versions.sh
   rules:
     - changes:
         - "*/PKGBUILD"
+        - "*/.CI_CONFIG"
       if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
 
-deploy:
-  # This only runs on the default branch and when the commit message contains [deploy *]
-  # and is used to deploy the package to the build server.
+push-pkgbuild:
   stage: deploy
   image: alpine:latest
+  before_script:
+    - '[[ -z ${AUR_KEY+x} ]] && echo "No AUR SSH key available, backing off!" && exit 1'
+    - mkdir /root/.ssh
+    - echo "$AUR_KEY" >/root/.ssh/id_rsa
+    - chmod 600 /root/.ssh/id_rsa
+    - apk add --no-cache --upgrade bash git openssh rsync
   script:
-    - '[[ -z ${DEPLOY_KEY+x} ]] && echo "No deploy key available, backing off!" && exit 1'
-    - mkdir -p ~/.ssh
-    - chmod 700 ~/.ssh
-    - echo "$DEPLOY_KEY" >>~/.ssh/id_ed25519
-    - chmod 400 ~/.ssh/id_ed25519
-    - apk add --no-cache --upgrade bash openssh
-    - bash .ci/what-to-deploy.sh
-    - bash .ci/deploy.sh
-  artifacts:
-    name: $CI_JOB_NAME-$CI_COMMIT_REF_NAME
-    when: on_failure
-    paths:
-      - "*.log"
+    - git config --global user.name "Chaotic-AUR CI"
+    - git config --global user.email "$GIT_AUTHOR_EMAIL"
+    # This script determines whether a relevant change occurred and if so, pushes the package to AUR
+    - bash .ci/manage-aur.sh
   rules:
-    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH && $CI_COMMIT_MESSAGE =~ /\[deploy.*\]/ && $BUMPVER != "1"
+    - changes:
+        - "*/.SRCINFO"
+        - "*/PKGBUILD"
+      if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
