chore(packages): update packages

diff --git a/mhwd-nvidia/mhwd-nvidia b/mhwd-nvidia/mhwd-nvidia
--- a/mhwd-nvidia/mhwd-nvidia
+++ b/mhwd-nvidia/mhwd-nvidia
@@ -20,15 +20,13 @@ set -e
 # upgrading to a new release of the nvidia driver, though.
 
 if [ "$#" -ne 2 ]; then
-  printf >&2 'USAGE: %s README.txt nv-kernel.o\n' "$0"
+  >&2 printf 'USAGE: %s README.txt nv-kernel.o\n' "$0"
   exit 1
 fi
 
 device_ids() {
-  local readme="$1"
-  shift
-  local object="$1"
-  shift
+  local readme="$1"; shift
+  local object="$1"; shift
 
   local ret=1
 
@@ -44,19 +42,19 @@ device_ids() {
   local readme_length="$(grep -Ec . "$readme_list")"
 
   objdump --section=.rodata --syms "$object" |
-    sed -nr '/SYMBOL TABLE/,/^$/ {
+  sed -nr '/SYMBOL TABLE/,/^$/ {
     s/^([0-9a-f]+)\s+l\s+O\s+\S+\s+([0-9a-f]+)\s+\S+.*/\2 \1/p
   }' |
-    sort -nr >"$symbols" # The list is probably among the larger symbols.
+  sort -nr >"$symbols" # The list is probably among the larger symbols.
 
   while read length start; do
     [ "$((0x$length))" -gt 0 ] || continue
 
     objdump --section=.rodata --full-contents \
       --start-address="0x$start" \
-      --stop-address="$((0x$start + 0x$length))" "$object" |
-      sed -nr 's/^ [0-9a-f]+ ([0-9a-f]{2})([0-9a-f]{2}).*/\2\1/p' |
-      sort | uniq | (grep -vx 0000 || :) >"$object_list"
+      --stop-address="$((0x$start+0x$length))" "$object" |
+    sed -nr 's/^ [0-9a-f]+ ([0-9a-f]{2})([0-9a-f]{2}).*/\2\1/p' |
+    sort | uniq | (grep -vx 0000 || :) >"$object_list"
 
     local object_length="$(grep -Ec . "$object_list")"
 
@@ -66,8 +64,8 @@ device_ids() {
 
     # Some thresholds for now.
     if [ "$num_deletions" -eq 0 ] &&
-      [ "$num_additions" -le "$(($readme_length * 3 / 2))" ]; then
-      printf >&2 'DEBUG: readme:%d object:%d deletions:%d additions:%d\n' \
+       [ "$num_additions" -le "$(($readme_length*3/2))" ]; then
+      >&2 printf 'DEBUG: readme:%d object:%d deletions:%d additions:%d\n' \
         "$readme_length" "$object_length" "$num_deletions" "$num_additions"
       ret=0
       break
@@ -82,7 +80,7 @@ device_ids() {
     done <"$object_list"
 
   else
-    printf >&2 '%s\n' 'Failed to find the list. Using README.txt to get the list'
+    >&2 printf '%s\n' 'Failed to find the list. Using README.txt to get the list'
 
     # We failed to extract the ids from the blob. Use the ones in README.txt
     # as a fallback
