feat(garuda-update): Implement new emergency hotfixes system, ditch garuda-hotfixes

diff --git a/garuda-update/garuda-update b/garuda-update/garuda-update
--- a/garuda-update/garuda-update
+++ b/garuda-update/garuda-update
@@ -2,34 +2,74 @@
 # shellcheck disable=SC2015
 set -e
 
-minimal_pacman_conf() {
-	local TEMP_CONF
-	TEMP_CONF=$(mktemp)
-	echo -e "[chaotic-aur]\nServer = https://garudalinux.org/os/garuda-update/backuprepo/x86_64" >"$TEMP_CONF"
-	echo "$TEMP_CONF"
+VERSION_FLAG=7
+
+emergency_hotfix() {
+	local HOTFIX_VERSION_CHECK
+
+	# Check https://garudalinux.org/os/garuda-update/hotfix-check
+	if ! HOTFIX_VERSION_CHECK="$(wget --timeout=15 -qO- https://garudalinux.org/os/garuda-update/hotfix-check)" || [[ ! "$HOTFIX_VERSION_CHECK" =~ ^[0-9]+$ ]]; then
+		return
+	fi
+
+	# Check if VERSION_FLAG is lower than the hotfix version
+	if (( VERSION_FLAG >= HOTFIX_VERSION_CHECK )); then
+		return
+	fi
+
+	local HOTFIX
+	if ! HOTFIX="$(wget --timeout=15 -qO- https://garudalinux.org/os/garuda-update/hotfix)" || [[ "${HOTFIX%%$'\n'*}" != "# GARUDA UPDATE HOTFIX" ]]; then
+		return
+	fi
+
+	$INT || return
+
+	local choice
+	echo -e "\n\033[1;33mUnable to perform a self-update to the latest version of garuda-update.\033[0m"
+	echo -e "\033[1;34mThe Garuda Linux development team has flagged this version of garuda-update as needing outside assistance to initiate a system update.\033[0m"
+	echo -e "\033[1;34mTo successfully update the system, it may be necessary to execute the Garuda Linux development team recommended hotfix script from the internet.\033[0m"
+	while true; do
+		echo -e "\033[1;32mDo you want to run the hotfix script now? (y/n/p = show script) \033[0m"
+		read -r choice
+		$INT || return
+		case $choice in
+			y|Y) break ;;
+			n|N) return ;;
+			p|P) echo "$HOTFIX" ;;
+			*) echo "Invalid choice. Please enter y, n, or p." ;;
+		esac
+	done
+	local retcode=0
+	VERSION=${VERSION_FLAG} bash <<< "$HOTFIX"
+	retcode=$?
+	if (( retcode != 0 )); then
+		exit $retcode
+	else
+		exec /usr/bin/garuda-update "$@"
+	fi
 }
 
 self_update() {
+	if [ -v SELF_UPDATE_FAIL ]; then
+		unset SELF_UPDATE_FAIL
+	fi
 	# Let the update script self update
-	local EXTRA_PARAMS=()
 	if [ "$DATABASE_UPDATED" == "force" ]; then
 		$PACMAN -Syy && DATABASE_UPDATED=true || true
 	elif [ "$DATABASE_UPDATED" != "true" ]; then
 		$PACMAN -Sy && DATABASE_UPDATED=true || true
 	fi
-	[ "$DATABASE_UPDATED" != "true" ] && local MIN_PACMAN_CONF && MIN_PACMAN_CONF="$(minimal_pacman_conf)" && $PACMAN --config "$MIN_PACMAN_CONF" -Syy && EXTRA_PARAMS=("--config" "$MIN_PACMAN_CONF") || true
+	if [ "$DATABASE_UPDATED" != "true" ]; then
+		SELF_UPDATE_FAIL=1
+	fi
 	$INT
-	if $PACMAN "${EXTRA_PARAMS[@]}" -Qu garuda-update &>/dev/null; then
-		local success=true
-		if ! SNAP_PAC_SKIP=y SKIP_AUTOSNAP='' $PACMAN "${EXTRA_PARAMS[@]}" -Sdd garuda-update --needed --noconfirm; then
-			$INT
-			# Create unshare'd mount namespace and mount an empty tmpfs on /usr/share/libalpm/hooks and /var/cache/pacman/pkg if it exists
-			unshare -m bash -c 'mount -t tmpfs tmpfs /usr/share/libalpm/hooks && { [ ! -d /var/cache/pacman/pkg ] || mount -t tmpfs tmpfs /var/cache/pacman/pkg; } && eval "$@"' -- SNAP_PAC_SKIP=y SKIP_AUTOSNAP='' "$PACMAN" "${EXTRA_PARAMS[@]}" --hookdir "/usr/share/libalpm/hooks" -Sdd garuda-update --needed --noconfirm || success=false
+	if $PACMAN -Qu garuda-update &>/dev/null; then
+		if SNAP_PAC_SKIP=y SKIP_AUTOSNAP='' $PACMAN -Sdd garuda-update --needed --noconfirm; then
+			GARUDA_UPDATE_SELFUPDATE="$VERSION_FLAG" exec /usr/bin/garuda-update "$@"
+		else
+			SELF_UPDATE_FAIL=1
 		fi
 		$INT
-		if [ "$success" == "true" ]; then
-			GARUDA_UPDATE_SELFUPDATE=2 exec /usr/bin/garuda-update "$@"
-		fi
 	fi
 	# Check if we have received sigint and should exit
 	$INT
@@ -53,7 +93,7 @@ fi
 
 # Run the "I'm too lazy to fix it myself all in one" script
 if [ "$1" == "remote" ]; then
-	exec bash -c "VERSION=6 . <(wget -qO- https://garudalinux.org/os/garuda-update/remote-update) \"\$@\"" remote-update "${@:2}"
+	exec bash -c "VERSION=${VERSION_FLAG} . <(wget -qO- https://garudalinux.org/os/garuda-update/remote-update) \"\$@\"" remote-update "${@:2}"
 fi
 
 if [ -n "$PACMAN_EXE" ]; then
@@ -70,6 +110,10 @@ if [ -n "$GARUDA_UPDATE_SELFUPDATE" ]; then
 fi
 
 self_update "$@"
+
+if [ -v SELF_UPDATE_FAIL ]; then
+	emergency_hotfix
+fi
 
 # shellcheck source=./main-update
 source /usr/lib/garuda/garuda-update/main-update
