fix(garuda-update): Do not run aur updates on firefly
Previous implementation was broken. Oops.

diff --git a/garuda-update/main-update b/garuda-update/main-update
--- a/garuda-update/main-update
+++ b/garuda-update/main-update
@@ -227,23 +227,23 @@ do_update
 
 /usr/lib/garuda/garuda-update/update-helper-scripts post-update-routines
 
-if [[ -v UPDATE_AUR ]] && [[ -z "$GARUDA_UPDATE_RANI" ]]; then
-  # Check for AUR helper
-  if [ -x /usr/bin/paru ] && [[ -n "$SUDO_UID" ]]; then
-    echo -e "\n\033[1;33m-->\033[1;34m Updating AUR packages with paru..\033[0m"
-    sudo -u "#$SUDO_UID" paru -Sua || { echo -e "\033[1;31m\nParu exited with error code $?\n\033[0m"; }
-  elif [ -x /usr/bin/yay ] && [[ -n "$SUDO_UID" ]]; then
-    echo -e "\n\033[1;33m-->\033[1;34m Updating AUR packages with yay..\033[0m"
-    sudo -u "#$SUDO_UID" yay -Sua || { echo -e "\033[1;31m\nYay exited with error code $?\n\033[0m"; }
+if [[ -v UPDATE_AUR ]]; then
+  if [ -v GARUDA_UPDATE_RANI ] || [ -v FIREFLY_PACKAGE_MANAGER ]; then
+    # In this case we must not attempt running the update. There is no way to confirm/review updates as of today.
+    echo -e "\n\033[1;33m-->\033[1;34m Skipping AUR update. Running those via Rani is explicitly not supported. Instead, use the terminal and review updates manually.\033[0m"
   else
-    echo -e "\n\033[1;33m--> UPDATE_AUR specified but no supported AUR helper found ❌\033[0m"
+    # Check for AUR helper
+    if [ -x /usr/bin/paru ] && [[ -n "$SUDO_UID" ]]; then
+      echo -e "\n\033[1;33m-->\033[1;34m Updating AUR packages with paru..\033[0m"
+      sudo -u "#$SUDO_UID" paru -Sua || { echo -e "\033[1;31m\nParu exited with error code $?\n\033[0m"; }
+    elif [ -x /usr/bin/yay ] && [[ -n "$SUDO_UID" ]]; then
+      echo -e "\n\033[1;33m-->\033[1;34m Updating AUR packages with yay..\033[0m"
+      sudo -u "#$SUDO_UID" yay -Sua || { echo -e "\033[1;31m\nYay exited with error code $?\n\033[0m"; }
+    else
+      echo -e "\n\033[1;33m--> UPDATE_AUR specified but no supported AUR helper found ❌\033[0m"
+    fi
+    $INT
   fi
-  $INT
-fi
-
-if [[ -v UPDATE_AUR ]] && [[ -v GARUDA_UPDATE_RANI ]] && [[ -v FIREFLY_PACKAGE_MANAGER ]]; then
-  # In this case we must not attempt running the update. There is no way to confirm/review updates as of today.
-  echo -e "\n\033[1;33m-->\033[1;34m Skipping AUR update. Running those via Rani is explicitly not supported. Instead, use the terminal and review updates manually.\033[0m"
 fi
 
 /usr/lib/garuda/garuda-update/update-helper-scripts end-routines
