feat(garuda-update): Change mirrorlist logic to be more robust

diff --git a/garuda-update/main-update b/garuda-update/main-update
--- a/garuda-update/main-update
+++ b/garuda-update/main-update
@@ -41,6 +41,44 @@ parse_pacman_log() {
 	esac
 }
 
+update_mirrorlist() {
+	if [[ -v SKIP_MIRRORLIST ]]; then
+		return
+	fi
+
+	local MIRRORLIST_TEMP MINLINES=0
+	MIRRORLIST_TEMP="$(mktemp)"
+	if command -v rate-mirrors >/dev/null; then
+		MINLINES=10
+		echo -e "\n\033[1;33m-->\033[1;34m Refreshing mirrorlists using rate-mirrors, please be patient..🍵\033[0m\n"
+		# Refresh mirrorlist and make sure it actually contains content. There is a bug in rate-mirrors that creates empty files sometimes.
+		rate-mirrors --allow-root --save="$MIRRORLIST_TEMP" arch --max-delay=21600 >/dev/null || { rm "$MIRRORLIST_TEMP"; }
+		$INT
+	elif command -v reflector >/dev/null; then
+		MINLINES=5
+		echo -e "\n\033[1;33m-->\033[1;34m Refreshing mirrorlists using reflector, please be patient..🍵\033[0m\n"
+		reflector --latest 10 --age 2 --fastest 10 --protocol https --sort rate --save "$MIRRORLIST_TEMP" || { rm "$MIRRORLIST_TEMP"; }
+		$INT
+	else
+		return
+	fi
+
+	if [ ! -f "$MIRRORLIST_TEMP" ]; then
+		echo -e "\033[1;31m\nFailed to update mirrorlist\n\033[0m";
+		return
+	fi
+
+	if COUNT="$(grep -Ec "^Server *=" "$MIRRORLIST_TEMP")" && [ "$COUNT" -ge "$MINLINES" ]; then
+		install -m644 "$MIRRORLIST_TEMP" /etc/pacman.d/mirrorlist
+		DATABASE_UPDATED="force"
+	else
+		echo -e "\033[1;31m\nNew mirrorlist does not contain enough mirrors. Skipping mirrorlist update.\n\033[0m"
+		return
+	fi
+
+	rm "$MIRRORLIST_TEMP"
+}
+
 do_update() {
 	if [ -x /usr/bin/expect ]; then
 		local AUTOPACMAN_LOG EXIT=0 RETRY=false CUSTOM_PACMAN_CONFIG="" SUCCESS=false
@@ -142,32 +180,15 @@ init_logging
 # Add garuda repo if it doesn't exist
 /usr/lib/garuda/garuda-update/update-helper-scripts migrate-garuda-repo && DATABASE_UPDATED=false || true
 
-if [[ ! -v SKIP_MIRRORLIST ]]; then
-	# Refresh mirrorlists
-	if [ -x /usr/bin/rate-mirrors ]; then
-		echo -e "\n\033[1;33m-->\033[1;34m Refreshing mirrorlists using rate-mirrors, please be patient..🍵\033[0m\n"
-		# Refresh mirrorlist and make sure it actually contains content. There is a bug in rate-mirrors that creates empty files sometimes.
-		MIRRORLIST_TEMP="$(mktemp)"
-		RATE_MIRRORS_COMPLETION=0.98 rate-mirrors --allow-root --save="$MIRRORLIST_TEMP" arch --max-delay=21600 >/dev/null &&
-			grep -qe "^Server = http" "$MIRRORLIST_TEMP" && install -m644 "$MIRRORLIST_TEMP" /etc/pacman.d/mirrorlist && $PACMAN -Syy && DATABASE_UPDATED=true || { echo -e "\033[1;31m\nFailed to update mirrorlist\033[0m"; }
-		rm -f "$MIRRORLIST_TEMP"
-		$INT
-	elif [ -x /usr/bin/reflector ]; then
-		echo -e "\n\033[1;33m-->\033[1;34m Refreshing mirrorlists using reflector, please be patient..🍵\033[0m\n"
-
-		reflector --completion-percent 98 --latest 5 --age 2 --fastest 5 --protocol https --sort rate --save /etc/pacman.d/mirrorlist &&
-			$INT && $PACMAN -Syy && DATABASE_UPDATED=true || { echo -e "\033[1;31m\nFailed to update mirrorlist\n\033[0m"; }
-		$INT
-	fi
-fi
-
+# Update mirrorlist and recheck if we need to update garuda-update
+update_mirrorlist
 self_update "$@"
 
 # Run pre-update routines and hotfixes
 /usr/lib/garuda/garuda-update/update-helper-scripts pre-update-routines
 
 pacman_args=("-Su")
-if [ "$DATABASE_UPDATED" == false ]; then pacman_args+=("-y"); fi
+if [ "$DATABASE_UPDATED" == false ]; then pacman_args+=("-y"); elif [ "$DATABASE_UPDATED" == "force" ]; then pacman_args+=("-yy"); fi
 while IFS= read -r line; do
 	pacman_args+=("$line")
 done < <(/usr/lib/garuda/garuda-update/update-helper-scripts package-replaces)
