fix(garuda-update): Fix edge case in which garuda-update would loop forever on an unknown key

diff --git a/garuda-update/update-helper-scripts b/garuda-update/update-helper-scripts
--- a/garuda-update/update-helper-scripts
+++ b/garuda-update/update-helper-scripts
@@ -18,8 +18,10 @@ update_keyrings() {
 	if [ -n "$($PACMAN -Qu "${packages[@]}" 2>&1)" ]; then
 		echo -e "\n\033[1;33m-->\033[1;34m Applying keyring updates before starting full system update..\033[0m"
 		# shellcheck disable=1007
-		SNAP_PAC_SKIP=y SKIP_AUTOSNAP= $PACMAN -S --needed --noconfirm "${packages[@]}" || false
+		SNAP_PAC_SKIP=y SKIP_AUTOSNAP= $PACMAN -S --needed --noconfirm "${packages[@]}" || return 0
+		return 1
 	fi
+	return 0
 }
 
 # If we are dealing with a more legacy garuda install, we should auto install expect to get auto-pacman working.
@@ -80,10 +82,16 @@ package-replaces() {
 	fi
 }
 
+# Exit codes:
+# 0: Everything is fine
+# 1: Something went wrong
+# 2: Keyring updated
 pre-update-routines() {
-	update_keyrings
+	local exit_code=0
+	update_keyrings || exit_code=2
 	install_expect
 	remove-chaotic-kf5-dummy
+	return $exit_code
 }
 
 migrate-garuda-repo() {
@@ -187,3 +195,4 @@ verify-core() {
 }
 
 "$@"
+exit "$?"
